{{- range $cm, $data := .Values.configMaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $cm }}
  labels:
    {{- include "coop-app-chart.labels" . | nindent 4 }}
data:
  {{- $data.data | toYaml | nindent 2}}
{{- end }}
