apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "coop-app-chart.name" . }}
  labels:
    {{- include "coop-app-chart.deploymentLabels" . | nindent 4 }}
  annotations:
    kube-score/ignore: {{ .Values.advanced.deployment.kubeScoreIgnore | join "," }}
spec:
  {{- if not .Values.scaling.autoScalingEnabled }}
  replicas: {{ .Values.scaling.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "coop-app-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "coop-app-chart.podLabels" . | nindent 8 }}
      annotations:
        proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
        sidecar.istio.io/proxyMemory: {{ .Values.resources.istioProxyMemory  | default "64Mi" }}
        sidecar.istio.io/proxyMemoryLimit: {{ .Values.resources.istioProxyMemoryLimit  | default "1Gi" }}
        sidecar.istio.io/proxyCPU: {{ .Values.resources.istioProxyCpu  | default "20m" }}
        sidecar.istio.io/proxyCPULimit: {{ .Values.resources.istioProxyCpuLimit  | default "1000m" }}
    spec:
      serviceAccountName: {{ .Values.name }}
      securityContext:
        {{- toYaml .Values.advanced.deployment.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.name }}
          securityContext:
            {{- toYaml .Values.advanced.deployment.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ required "A valid .Values.image.repository is required!" .Values.image.repository }}:{{ required "A valid .Values.image.tag is required!" .Values.image.tag }}"
          imagePullPolicy: Always
          env: 
            - name: DD_DOGSTATSD_URL
              value: "unix:///var/run/datadog/dsd.socket"
            - name: DD_TRACE_AGENT_URL
              value: "/var/run/datadog/apm.socket"
            - name: DD_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/env']
            - name: DD_SERVICE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/service']
            - name: DD_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/version']
            {{- if .Values.connectivity.gRPCGateway.enabled }}
            - name: GRPC_GW_PORT
              value: "{{ .Values.connectivity.gRPCGateway.portOverride | default (.Values.port | add1f)  }}"
            {{- end }}
            - name: PORT
              value: "{{ .Values.port }}"
            {{- range $key, $value := .Values.environmentVariables }}
            - name: {{ $key }}
              {{- if contains "\n" $value }}
              value: {{ $value | toJson }}
              {{- else }}
              value: "{{ $value }}"
              {{- end }}
            {{- end }}
            {{- range $secretObject, $value := .Values.secrets }}
            {{- range $secretKey, $_ := $value.secrets }}
            - name: {{ $secretKey }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secretObject }}
                  key: {{ $secretKey }}
            {{- end }}
            {{- end }}
            {{- range $configMap, $value := .Values.configMaps }}
            {{- range $key, $_ := $value.data }}
            - name: {{ $key }}
              valueFrom:
                configMapRef:
                  name: {{ $configMap }}
                  key: {{ $key }}
            {{- end }}
            {{- end }}

          ports:
            - name: {{ include "coop-app-chart.portName" . }}
              containerPort: {{ .Values.port }}
              protocol: TCP
            {{- if .Values.connectivity.gRPCGateway.enabled }}
            - name: grpc-gateway
              containerPort: {{ .Values.connectivity.gRPCGateway.portOverride | default (.Values.port | add1f)  }}
              protocol: TCP
            {{- end }}
          livenessProbe:
            {{- if .Values.health.livenessProbe -}}
            {{ .Values.health.livenessProbe | toYaml | nindent 12}}
            {{- else if .Values.connectivity.gRPC.enabled }}
            # istio 1.10.2 does not support grpc health, fallback to tcp for now
            tcpSocket:
              port: {{ .Values.port }}
            {{- else }} 
            httpGet:
              path: {{ .Values.health.path | default "/" }}
              port: {{ .Values.health.port | default .Values.port }}
            {{- end }}
          readinessProbe:
            {{- if .Values.health.readinessProbe -}}
            {{ .Values.health.readinessProbe | toYaml | nindent 12}}
            {{- else if .Values.connectivity.gRPC.enabled }}
            # istio 1.10.2 does not support grpc health, fallback to tcp for now
            tcpSocket:
              port: {{ .Values.port }}
            {{- else }} 
            httpGet:
              path: {{ .Values.health.path | default "/" }}
              port: {{ .Values.health.port | default .Values.port }}
            {{- end }}
          volumeMounts:
            - name: dsdsocket
              mountPath: /var/run/datadog
              readOnly: true
          resources:
            limits:
              memory: {{ .Values.resources.memory }}
            requests:
              memory: {{ .Values.resources.memory }}
              cpu: {{ .Values.resources.cpu }}
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.gke.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            {{- include "coop-app-chart.selectorLabels" . | nindent 12 }}
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            {{- include "coop-app-chart.selectorLabels" . | nindent 12 }}
      {{- with .Values.advanced.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.advanced.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.advanced.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - hostPath:
            path: /var/run/datadog/
          name: dsdsocket
