{{ $root := . }}
{{- range $es, $data := .Values.secrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $es }}
  labels:
    {{- include "coop-app-chart.labels" $root | nindent 4 }}
spec:
  secretStoreRef:
    kind: SecretStore
    name: {{ $data.provider }}
  target:
    name: {{ $es }}
  data:
  {{- range $key, $ref := $data.secrets }}
    - secretKey: {{ $key }}
      remoteRef:
        key: {{ $ref }}
  {{- end }}
{{- end }}
