apiVersion: v1
kind: Service
metadata:
  name: {{ include "coop-app-chart.name" . }}
  labels:
    {{- include "coop-app-chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
      name: {{ include "coop-app-chart.portName" . }}
      appProtocol: {{ include "coop-app-chart.appProtocol" . }}  
    {{- if .Values.connectivity.gRPCGateway.enabled }}
    - name: grpc-gateway
      port: {{ .Values.connectivity.gRPCGateway.portOverride | default (.Values.port | add1f)  }}
      protocol: TCP
      targetPort: {{ .Values.connectivity.gRPCGateway.portOverride | default (.Values.port | add1f)  }}
      appProtocol: http
    {{- end }}
  selector:
    {{- include "coop-app-chart.selectorLabels" . | nindent 4 }}
