name: # the name of the service 

environment: # environment to which you deploy for ex production or staging

image:
  repository: # the repository where the image is stored
  tag: # the tag of the image
  pullPolicy: Always # the policy to pull the image
  
port: # the port on which the service is going to run

environmentVariables: {}
  #ENV_NAME: Value


health: {}
  #if .connectivity.gRPC.enabled it will use a tcpSocket as health check. Will be moved to native gRPC healthcheck when available.
  #path: / # defaults to '/' if http is enabled
  #livenessProbe: livenessprobe override, use native format
  #readinessProbe: readynessprobe override, use native format
    

scaling:
  replicas: 2 
  autoScalingEnabled: true
  maxReplicas: 4
  scalingCpuPercentage: 80 
  scalingMemoryPercentage: 80 

resources:
  memory: 64M
  cpu: 200m

configMaps: {}
  #configMapName:
  #  data:
  #    keyname: value 
  #    longvaluekey: |
  #        some long value
  #    mountAsEnvironment: false
  #    mountAsVolume: false (not yet implemented)
  #    mountVolumePath: (not yet implemented)

secrets: {} # required external secret manager
  #secretObjectName:
  #  provider: gcp (where secrets are stored) 
  #    secrets:
  #      key-name: secret-id
  #    mountAsEnvironment: false
  #    mountAsVolume: false (not yet implemented)
  #    mountVolumePath: (not yet implemented)


connectivity:
  http:
    # do not enable if you just want to publish gRPC has http. Check 
    # connectivity.gRPC.publishAsHTTP
    enabled: false
    dns: api.coop.no 
    #path: # defaults to name (or app.name in case this chart is used as dependency) 
    rewrite: / 
    additionalEndpoints: [] # not yet implemented
      # - dns: 
      #   path: app.name (default)
      #   rewrite: / (default)
  gRPC:
    enabled: false
    dns: api.coop.no
    # Sets on which prefix of a path use use for routing requests to this app.  
    # pathMatchter: defaults to "/coopnorge.<name>."
 
  externalServices: {} #white list to services
  #  github:
  #    hosts:
  #        - github.com
  #        - www.github.com 
  #        - api.github.com
  #      ports:
  #        - name: https
  #          number: 443
  #          protocol: https

 
  httpToGRPC:
    # !! Note: This is susceptible to change.
    enabled: false
    dns: api.coop.no
    # protoDescriptorBinValue: base64 encoded value of the proto descriptor bin
    protoDescriptorBinValue:  
    # services: list of gRPC services packaged in the proto descriptor
    services: []  

# advanced configuration 
# This exposes some configuration options which an user 
# generaly should not change. 
advanced:
  deployment:
    kubeScoreIgnore: 
      - pod-probes
      - pod-networkpolicy 
      - deployment-has-poddisruptionbudget
      - container-resources
      - deployment-has-host-podantiaffinity
      - container-ephemeral-storage-request-and-limit
    podSecurityContext:       
      fsGroup: 65534    
     
    securityContext:
      capabilities:
        drop:
          - ALLL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 65534
      runAsGroup: 65534    

 
