{{- if gt (.Values.scaling.replicas | int) 1  }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "coop-app-chart.name" . }}
spec:
  minAvailabe: {{ sub (.Values.scaling.replicas | int) 1 }}
  selector:
    matchLabels:
    {{- include "coop-app-chart.selectorLabels" . | nindent 6 }}
{{- end }}

