apiVersion: v1
kind: Service
metadata:
  name: {{ include "coop-app-chart.name" . }}
  labels:
    {{- include "coop-app-chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
      name: {{ include "coop-app-chart.portName" . }}
  selector:
    {{- include "coop-app-chart.selectorLabels" . | nindent 4 }}
