on:
  push: {}
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    needs:
      - validate
      - supply-chain-security-validation
    steps:
      - run: "echo SUCCESS"
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Output message
        run: echo howdi
  supply-chain-security-validation:
    name: Supply Chain Security Validation
    uses: coopnorge/github-workflow-supply-chain-security-validation/.github/workflows/supply-chain-security-validation.yaml@main
