on:
  push: {}
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    needs:
      - validate
      - supply-chain-security-validation
    steps:
      - run: "echo SUCCESS"
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Output message
        run: echo This is a default job to trigger output but it fails
      - name: Fail when not in template
        if: ${{ github.repository != 'coopnorge/github-template-default' }}
        run: exit 1
  supply-chain-security-validation:
    name: Supply Chain
    uses: coopnorge/github-workflow-supply-chain-security-validation/.github/workflows/supply-chain-security-validation.yaml@main