on:
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    needs:
      - validate
    steps:
      - run: "echo SUCCESS"
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Output message
        run: echo Howdy
