name: Release drafter

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited

permissions:
  contents: read

jobs:
  release-draft:
    permissions:
      pull-requests: write
      contents: write
    uses: coopnorge/github-workflow-release-drafter/.github/workflows/release-drafter.yaml@v0.3.1

  process-release-output:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: release-draft
    outputs:
      tag_name: ${{ steps.get-version.outputs.tag_name }}
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - id: get-version
        run: |
          RELEASE_VERSION=${{ needs.release-draft.outputs.name }}
          RELEASE_VERSION=${RELEASE_VERSION#v}
          echo "version=$RELEASE_VERSION" >> "$GITHUB_ENV"
          
          TAG_NAME=${{ needs.release-draft.outputs.tag_name }}
          echo "tag_name=$TAG_NAME" >> "$GITHUB_ENV"

  release-alpha-version:
    permissions:
      contents: write
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/release-chart-workflow.yaml
    needs: process-release-output
    with:
      repository: ${{ github.repository }}
      release-tag: ${{ needs.process-release-output.outputs.tag_name }}
      release-version: ${{ needs.process-release-output.outputs.version }}-alpha.${{ github.event.pull_request.number }}.${{ github.run_number }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
