name: Release chart

on:
  release:
    types: [released]

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Get release version
        id: get_release_version
        run: |
          TAG="${{ github.event.release.tag_name }}"
          echo "release_tag=$TAG" >> "$GITHUB_OUTPUT"
          echo "release_version=${TAG#v}" >> "$GITHUB_OUTPUT"

      - name: Publish the release
        uses: ./.github/workflows/release-chart-workflow.yaml
        with:
          repository: ${{ github.repository }}
          release-tag: ${{ steps.get_release_version.outputs.release_tag }}
          release-version: ${{ steps.get_release_version.outputs.release_version }}
