name: Release drafter

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited

permissions:
  contents: read

jobs:
  release-draft:
    permissions:
      pull-requests: write
      contents: write
    uses: coopnorge/github-workflow-release-drafter/.github/workflows/release-drafter.yaml@v0.3.2

  process-release-drafter-output:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: release-draft
    outputs:
      tag_name: ${{ steps.get-version.outputs.tag_name }}
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - id: get-version
        run: |
          RELEASE_VERSION=${{ needs.release-draft.outputs.name }}-alpha.${{ github.event.pull_request.number }}.${{ github.run_number }}
          RELEASE_VERSION=${RELEASE_VERSION#v}
          echo "version=$RELEASE_VERSION" >> "$GITHUB_OUTPUT"

          echo "tag_name=${{ needs.release-draft.outputs.tag_name }}" >> "$GITHUB_OUTPUT"

  release-alpha-version:
    permissions:
      contents: write
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/release-chart-workflow.yaml
    needs: process-release-drafter-output
    with:
      repository: ${{ github.repository }}
      release-tag: ${{ needs.process-release-drafter-output.outputs.tag_name }}
      release-version: ${{ needs.process-release-drafter-output.outputs.version }}
      chart-path: charts/coop-app-chart
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  comment-pr:
    permissions:
      pull-requests: write
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: [release-alpha-version, process-release-drafter-output]
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ### 🚀 Alpha Version Published
            
            **Tag:** [${{ needs.process-release-drafter-output.outputs.tag_name }}](${{ needs.release-alpha-version.outputs.html-url }})
            
            **Chart version:** `${{ needs.process-release-drafter-output.outputs.version }}`
            
            **Chart filename:** `${{ needs.release-alpha-version.outputs.chart-filename }}`

            **Commit ID:** `${{ github.event.pull_request.head.sha }}`
