name: Release chart

on:
  release:
    types: [released]

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    outputs:
      release-tag: ${{ steps.get-release-version.outputs.release-tag }}
      release-version: ${{ steps.get-release-version.outputs.release-version }}
    steps:
      - name: Get release version
        id: get-release-version
        run: |
          TAG="${{ github.event.release.tag_name }}"
          echo "release-tag=$TAG" >> "$GITHUB_OUTPUT"
          echo "release-version=${TAG#v}" >> "$GITHUB_OUTPUT"

  publish-release:
    permissions:
      contents: write
    needs: prepare-release
    uses: ./.github/workflows/release-chart-workflow.yaml
    with:
      repository: ${{ github.repository }}
      release-tag: ${{ needs.prepare-release.outputs.release-tag }}
      release-version: ${{ needs.prepare-release.outputs.release-version }}
      chart-path: charts/coop-app-chart
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
